[package]
name = "rtm"
version = "0.1.0"
authors = ["Alex Parra <7588320-bluesden@users.noreply.gitlab.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
dirs = "3.0"
